version: "3.9"

services:
  ports:
   -80:80
  
  app:
    image: nginx:alpine
    networks:
      app_net:
        ipv4_address: 192.168.1.230
        ipv6_address: 2001:3984:3989::10

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.101"
        - subnet: "2001:3984:3989::/64"
